-- Customer Environment

CREATE OR REPLACE TABLE CORTEX.PUBLIC.CUSTOMER_DIM (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR
);

INSERT INTO CORTEX.PUBLIC.CUSTOMER_DIM VALUES
(1, 'John Smith'),
(2, 'Sarah Johnson'),
(3, 'Michael Chen');

CREATE OR REPLACE TABLE CORTEX.PUBLIC.CUSTOMER_SALES(
    CUSTOMER_ID INT,
    SALES INT
);

INSERT INTO CORTEX.PUBLIC.CUSTOMER_SALES VALUES
(1, 10),
(2, 20),
(3, 30);


CREATE OR REPLACE PROCEDURE CORTEX.PUBLIC.CREATE_SALES_FACT(SCHEMA_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    LET sql VARCHAR := '
        CREATE OR REPLACE TABLE ' || SCHEMA_NAME || '.SALES_FACT AS
        SELECT
            d.CUSTOMER_ID,
            d.CUSTOMER_NAME,
            SUM(s.SALES) AS TOTAL_SALES
        FROM ' || SCHEMA_NAME || '.CUSTOMER_DIM d
        INNER JOIN ' || SCHEMA_NAME || '.CUSTOMER_SALES s
            ON d.CUSTOMER_ID = s.CUSTOMER_ID
        GROUP BY d.CUSTOMER_ID, d.CUSTOMER_NAME';
    EXECUTE IMMEDIATE :sql;
    RETURN 'SALES_FACT table created successfully in ' || SCHEMA_NAME;
END;

CALL CORTEX.PUBLIC.CREATE_SALES_FACT('CORTEX.PUBLIC');







