-- Customer Environment

CREATE OR REPLACE TABLE CORTEX.PUBLIC.CUSTOMER_DIM (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR
);

INSERT INTO CORTEX.PUBLIC.CUSTOMER_DIM VALUES
(1, 'John Smith'),
(2, 'Sarah Johnson'),
(3, 'Michael Chen');

CREATE OR REPLACE TABLE CORTEX.PUBLIC.CUSTOMER_SALECORTEX.TESTING.CSV_STAGECORTEX.TESTING.CSV_STAGES (
    CUSTOMER_ID INT,
    SALES INT
);

INSERT INTO CORTEX.PUBLIC.CUSTOMER_SALES VALUES
(1, 10),
(2, 20),
(3, 30);


CREATE OR REPLACE PROCEDURE CORTEX.PUBLIC.CREATE_SALES_FACT()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    CREATE OR REPLACE TABLE CORTEX.PUBLIC.SALES_FACT AS
    SELECT
        d.CUSTOMER_ID,
        d.CUSTOMER_NAME,
        SUM(s.SALES) AS TOTAL_SALES
    FROM CORTEX.PUBLIC.CUSTOMER_DIM d
    INNER JOIN CORTEX.PUBLIC.CUSTOMER_SALES s
        ON d.CUSTOMER_ID = s.CUSTOMER_ID
    GROUP BY d.CUSTOMER_ID, d.CUSTOMER_NAME;
    RETURN 'SALES_FACT table created successfully';
END;

CALL CORTEX.PUBLIC.CREATE_SALES_FACT();

select * from cortex.public.sales_fact;


-- =============================================
-- TESTING SCHEMA: CSV Load + Procedure + Compare
-- =============================================

CREATE OR REPLACE TABLE CORTEX.TESTING.CUSTOMER_DIM (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR
);

CREATE OR REPLACE TABLE CORTEX.TESTING.CUSTOMER_SALES (
    CUSTOMER_ID INT,
    SALES INT
);

INSERT INTO CORTEX.TESTING.CUSTOMER_DIM (CUSTOMER_ID, CUSTOMER_NAME)
SELECT $1::INT, $2::VARCHAR
FROM @CORTEX.TESTING.CSV_STAGE/customer_dim.csv;

INSERT INTO CORTEX.TESTING.CUSTOMER_SALES (CUSTOMER_ID, SALES)
SELECT $1::INT, $2::INT
FROM @CORTEX.TESTING.CSV_STAGE/customer_sales.csv;

CREATE OR REPLACE PROCEDURE CORTEX.TESTING.CREATE_SALES_FACT()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    CREATE OR REPLACE TABLE CORTEX.TESTING.SALES_FACT AS
    SELECT
        d.CUSTOMER_ID,
        d.CUSTOMER_NAME,
        SUM(s.SALES) AS TOTAL_SALES
    FROM CORTEX.TESTING.CUSTOMER_DIM d
    INNER JOIN CORTEX.TESTING.CUSTOMER_SALES s
        ON d.CUSTOMER_ID = s.CUSTOMER_ID
    GROUP BY d.CUSTOMER_ID, d.CUSTOMER_NAME;
    RETURN 'SALES_FACT table created successfully';
END;

CALL CORTEX.TESTING.CREATE_SALES_FACT();

CREATE OR REPLACE TABLE CORTEX.TESTING.SALES_FACT_CSV AS
SELECT $1::INT AS CUSTOMER_ID, $2::VARCHAR AS CUSTOMER_NAME, $3::INT AS TOTAL_SALES
FROM @CORTEX.TESTING.CSV_STAGE/sales_fact.csv;

SELECT
    COALESCE(p.CUSTOMER_ID, c.CUSTOMER_ID) AS CUSTOMER_ID,
    p.CUSTOMER_NAME AS PROC_CUSTOMER_NAME,
    c.CUSTOMER_NAME AS CSV_CUSTOMER_NAME,
    p.TOTAL_SALES AS PROC_TOTAL_SALES,
    c.TOTAL_SALES AS CSV_TOTAL_SALES,
    CASE
        WHEN p.CUSTOMER_ID IS NULL THEN 'IN CSV ONLY'
        WHEN c.CUSTOMER_ID IS NULL THEN 'IN PROC ONLY'
        WHEN p.TOTAL_SALES != c.TOTAL_SALES THEN 'SALES MISMATCH'
        WHEN p.CUSTOMER_NAME != c.CUSTOMER_NAME THEN 'NAME MISMATCH'
        ELSE 'MATCH'
    END AS COMPARISON_STATUS
FROM CORTEX.TESTING.SALES_FACT p
FULL OUTER JOIN CORTEX.TESTING.SALES_FACT_CSV c
    ON p.CUSTOMER_ID = c.CUSTOMER_ID
ORDER BY COALESCE(p.CUSTOMER_ID, c.CUSTOMER_ID);




